# Generated by Django 6.0.2 on 2026-03-12 04:09

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_type', models.CharField(choices=[('CDRRMO Fund', 'CDRRMO Fund'), ('Trust Fund', 'Trust Fund'), ('LDRRM Fund', 'LDRRM Fund'), ('SB#1', 'SB#1'), ('Quick Respond Fund', 'Quick Respond Fund')], default='CDRRMO Fund', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference_no', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('date_received', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=150)),
                ('plate_no', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_type', models.CharField(choices=[('Rescue Vehicle', 'Rescue Vehicle'), ('Mobile', 'Mobile'), ('Bus', 'Bus'), ('Ambulance', 'Ambulance'), ('Van', 'Van'), ('Equipment', 'Equipment'), ('Others', 'Others')], default='Rescue Vehicle', max_length=50)),
                ('section', models.CharField(choices=[('EMS', 'EMS'), ('SAR', 'SAR'), ('TLD', 'TLD'), ('Others', 'Others')], default='EMS', max_length=20)),
                ('status', models.CharField(choices=[('Serviceable', 'Serviceable'), ('Non Serviceable', 'Non Serviceable')], default='Serviceable', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FuelTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=150)),
                ('vehicle_type', models.CharField(choices=[('Rescue Vehicle', 'Rescue Vehicle'), ('Mobile', 'Mobile'), ('Bus', 'Bus'), ('Ambulance', 'Ambulance'), ('Van', 'Van'), ('Equipment', 'Equipment'), ('Others', 'Others')], default='Rescue Vehicle', max_length=50)),
                ('section', models.CharField(choices=[('EMS', 'EMS'), ('SAR', 'SAR'), ('TLD', 'TLD'), ('Others', 'Others')], default='EMS', max_length=20)),
                ('plate_no', models.CharField(blank=True, max_length=50, null=True)),
                ('driver_name', models.CharField(max_length=150)),
                ('destination', models.CharField(blank=True, max_length=150, null=True)),
                ('odometer', models.PositiveIntegerField(blank=True, null=True)),
                ('charge_invoice_no', models.CharField(max_length=100)),
                ('product', models.CharField(choices=[('Diesel', 'Diesel'), ('Regular', 'Regular'), ('Extra', 'Extra')], default='Diesel', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fund_source', models.CharField(choices=[('CDRRMO Fund', 'CDRRMO Fund'), ('Trust Fund', 'Trust Fund'), ('LDRRM Fund', 'LDRRM Fund'), ('SB#1', 'SB#1'), ('Quick Respond Fund', 'Quick Respond Fund')], default='CDRRMO Fund', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_transactions', to='fuel_app.vehicle')),
            ],
        ),
    ]
