# Generated by Django 6.0.2 on 2026-03-13 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_app', '0003_alter_fueltransaction_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fueltransaction',
            name='odometer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
