# Generated by Django 6.0.2 on 2026-03-27 03:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_app', '0004_alter_fueltransaction_odometer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fueltransaction',
            name='amount',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='fueltransaction',
            name='unit_price',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
    ]
