# Generated by Django 6.0.2 on 2026-03-31 00:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_app', '0005_alter_fueltransaction_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fueltransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='fueltransaction',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
