# Generated by Django 6.0.2 on 2026-03-31 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_app', '0006_alter_fueltransaction_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fueltransaction',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
