# Generated by Django 6.0.2 on 2026-03-31 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_app', '0007_alter_fueltransaction_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fueltransaction',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
