# Generated by Django 6.0.2 on 2026-04-10 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_app', '0008_alter_fueltransaction_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetallocation',
            name='reference_no',
        ),
    ]
