# Generated by Django 6.0.2 on 2026-04-23 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_app', '0009_remove_budgetallocation_reference_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='fueltransaction',
            name='fund_year',
            field=models.PositiveIntegerField(choices=[(2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029'), (2030, '2030')], default=2026),
        ),
        migrations.AlterField(
            model_name='fueltransaction',
            name='section',
            field=models.CharField(choices=[('EMS', 'EMS'), ('SAR', 'SAR'), ('TLD', 'TLD'), ('Admin', 'Admin'), ('CCC', 'CCC'), ('RPD', 'RPD'), ('Others', 'Others')], default='EMS', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='section',
            field=models.CharField(choices=[('EMS', 'EMS'), ('SAR', 'SAR'), ('TLD', 'TLD'), ('Admin', 'Admin'), ('CCC', 'CCC'), ('RPD', 'RPD'), ('Others', 'Others')], default='EMS', max_length=20),
        ),
    ]
